# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='\u9ed8\u8ba4\u7f51\u7ad9', max_length=200, verbose_name='\u7f51\u7ad9\u6807\u9898')),
                ('blog_keyword', models.TextField(default='\u9ed8\u8ba4\u5173\u952e\u8bcd', verbose_name='\u7f51\u7ad9\u5173\u952e\u8bcd')),
                ('blog_descript', models.TextField(default='\u9ed8\u8ba4\u63cf\u8ff0', verbose_name='\u7f51\u7ad9\u63cf\u8ff0')),
            ],
        ),
    ]
