# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, help_text='\u53ef\u9009\u9879\uff0c\u82e5\u4e3a\u7a7a\u5219\u6458\u53d6\u6b63\u6587\u524d200\u4e2a\u5b57\u7b26', max_length=200, null=True, verbose_name='\u6458\u8981\uff08\u53ef\u9009\uff09'),
        ),
    ]
