# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20180508_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_com', models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('body_com', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('time_com', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myarticle', to='myadmin.article')),
            ],
        ),
    ]
