# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.IntegerField(default=0),
        ),
    ]
